# ------------------------- Options -------------------------
mode                         : 0   # 0 for debug
description                  : net_1024
device                       : "3"
epochs                       : 40000
gammas                       : [0.1, 0.1, 0.1]
schedule                     : [10000, 20000, 30000]
learning_rate                : 0.001
optimizer                    : Adam
entirety                     : False
model                        : net_1024_detect
# ----------------------- God Save Me -----------------------
save_model                   : True
dampening                    : 0.9
lr_patience                  : 10
momentum                     : 0.9
decay                        : 0.0005
start_epoch                  : 0
print_freq                   : 10
checkpoint                   : 10
n_threads                    : 2
result                       : /hdd/yongxinw/Det/experiments
# --------------------------- match settings ----------------
threshold                    : 0.4
use_gt_match                 : True
use_gt_anchor_class          : True
use_gt_offsets               : True
show_aligned_anchors         : False
# --------------------------- Dataset settings --------------
SequenceID                   : ["TUD-Stadtmitte"]
#SequenceID                   : ["ETH-Bahnhof"]
# --------------------------- Anchor settings ---------------
anchor_heights               : [84, 126, 168]
anchor_widths                : [38, 48, 84]
#anchor_heights               : [126]
#anchor_widths                : [48]
iou_pos_threshold            : 0.4
iou_neg_threshold            : 0.2
classes                      : {"background": 0, "pedestrian": 1}
start_ct                     : 84
start_cl                     : 32
gapH                         : 81
gapW                         : 42
# --------------------------- End ---------------------------